export const content = {
  en: {
    nav: {
      features: "Features",
      how: "How it works",
      pricing: "Pricing",
      login: "Log in",
      cta: "Request Demo",
    },
    hero: {
      eyebrow: "🧬 Built exclusively for IVF labs",
      headline: "Smart Scheduling\nfor IVF Laboratories",
      sub: "Create, manage and optimise your fertility lab rotas with the only tool designed specifically for embryologists, andrologists and IVF lab managers.",
      cta1: "Request a Demo",
      cta2: "See how it works",
      badge1: "Mobile & desktop optimised",
      badge2: "No training required",
      badge3: "Designed by embryologists",
      badge4: "Auto implementation",
    },
    social: null,
    problem: {
      badge: "The Problem",
      title: "Spreadsheets weren't designed for IVF lab scheduling",
      sub: "Lab managers spend hours every week juggling availability, competencies and last-minute changes — with a constant risk of human error.",
      p1title: "Error-prone coverage",
      p1: "Manual rota creation leads to skill-gap failures that risk critical IVF procedures and patient outcomes.",
      p2title: "Hours wasted every week",
      p2: "Lab managers spend 3–5 hours per week building rotas — time that should go to science, not spreadsheets.",
      p3title: "Invisible competency gaps",
      p3: "Spreadsheets can't tell you whether the person you've scheduled is actually certified for that IVF procedure — a silent but direct risk to patients.",
    },
    solution: {
      badge: "The Solution",
      title: "LabRota automates the complexity away",
      sub: "Purpose-built for IVF laboratories — LabRota understands embryologist competencies, procedure coverage, and the critical nature of every single shift.",
    },
    features: {
      title: "Everything your IVF lab needs",
      sub: "Built from the ground up for fertility labs — not a generic scheduling tool with a healthcare skin.",
      items: [
        { title: "AI-Powered Setup", body: "Share your existing spreadsheets or rotas. Our AI reads them, extracts your staff, shifts and procedure assignments, and configures your lab automatically — go live in one session." },
        { title: "AI Smart Rotas", body: "One click and LabRota's AI organises your entire shift schedule — balancing workload, respecting approved leave, and ensuring every procedure has the right certified staff assigned." },
        { title: "Competency Enforcement", body: "LabRota knows which procedures each staff member is certified for and flags gaps in real time — no more guessing who can cover what." },
        { title: "Leave Management", body: "Staff request time off in the app, managers approve with one click — leave balances update automatically." },
        { title: "Holiday Balance", body: "Track entitlement and real-time leave balances for every staff member. Managers see team-wide holiday accruals at a glance — automatically updated as leave is requested, approved, and taken." },
        { title: "Drag & Drop Editing", body: "Fine-tune any AI-generated rota with a simple drag and drop. Skill gap warnings and coverage alerts update live as you move shifts around." },
        { title: "Shift Swap Requests", body: "Staff can request shift swaps directly from the app. Managers review and approve — coverage is maintained automatically and everyone is notified instantly." },
        { title: "Outlook Calendar Sync", body: "Connect staff Outlook calendars and out-of-office events automatically become leaves in LabRota — no manual entry, no missed absences." },
      ],
    },
    how: {
      badge: "How it works",
      title: "From setup to published rota in minutes",
      steps: [
        { title: "We import your existing rotas", body: "Send us your spreadsheets. Our AI extracts your staff, shift patterns and procedure certifications — your lab is pre-configured before your first login." },
        { title: "Generate with AI", body: "Hit Generate. LabRota's AI analyses staff availability, certified competencies and approved leave across your whole team and builds the optimal rota automatically — in under a minute." },
        { title: "Review & adjust", body: "Drag and drop to make tweaks. LabRota flags skill gaps and coverage shortfalls in real time as you edit." },
        { title: "Publish & notify", body: "Publish the rota with one click. Your team is instantly notified. Export to PDF or XLS for records." },
      ],
      stat1: { value: "70%", label: "less time building rotas", sub: "avg. vs. spreadsheet workflow" },
      stat2: { value: "< 1 min", label: "to generate a full rota", sub: "with AI — from blank to done" },
      stat3: { value: "0", label: "skill gaps missed", sub: "AI catches them all" },
    },
    pricing: {
      title: "Simple, transparent pricing",
      sub: "Pay per staff member. Scale up or down as your team grows.",
      monthly: "Monthly",
      annual: "Annual",
      save: "Save 2 months",
      staffLabel: "Staff members",
      perMonthUnit: "/month",
      perAnnualUnit: "/month, billed annually",
      perPersonRate: "€5 per staff member",
      promo: "Launch offer",
      features: [
        "AI-powered rota generation",
        "Shift swap requests",
        "Competency enforcement & skill gap detection",
        "Leave management & holiday balance tracking",
        "Outlook calendar sync",
        "PDF & XLS export",
        "AI-assisted lab setup from your existing rotas",
        "Priority support",
      ],
      cta: "Request a Demo",
    },
    cta: {
      title: "Ready to simplify your lab scheduling?",
      sub: "Join IVF laboratories that have replaced spreadsheets with smart, AI-powered rotas. Book a 30-minute demo — no commitment required.",
      btn: "Request a Demo",
    },
    footer: {
      tagline: "Smart scheduling for IVF laboratories.",
      product: "Product",
      legal: "Legal",
      contact: "Contact",
      links: {
        features: "Features",
        pricing: "Pricing",
        login: "Log in",
        privacy: "Privacy Policy",
        terms: "Terms of Service",
        gdpr: "GDPR",
      },
      copy: "© 2026 LabRota. All rights reserved.",
    },
  },
  es: {
    nav: {
      features: "Funciones",
      how: "Cómo funciona",
      pricing: "Precios",
      login: "Iniciar sesión",
      cta: "Solicitar Demo",
    },
    hero: {
      eyebrow: "🧬 Diseñado exclusivamente para labs IVF",
      headline: "Turnos inteligentes\npara laboratorios IVF",
      sub: "Crea, gestiona y optimiza las rotas de tu laboratorio de fertilidad con la única herramienta diseñada específicamente para embriólogos, andrólogos y responsables de lab IVF.",
      cta1: "Solicitar una Demo",
      cta2: "Ver cómo funciona",
      badge1: "Optimizado para móvil y escritorio",
      badge2: "Sin formación previa",
      badge3: "Diseñado por embriólogos",
      badge4: "Auto implementación",
    },
    social: null,
    problem: {
      badge: "El Problema",
      title: "Las hojas de cálculo no fueron diseñadas para planificar laboratorios IVF",
      sub: "Los responsables de laboratorio dedican horas cada semana a cuadrar disponibilidad, competencias y normativa — con el riesgo permanente del error humano.",
      p1title: "Cobertura propensa a errores",
      p1: "La creación manual de rotas genera fallos de cobertura que ponen en riesgo procedimientos IVF críticos y los resultados de los pacientes.",
      p2title: "Horas perdidas cada semana",
      p2: "Los responsables de lab dedican 3-5 horas semanales construyendo rotas — tiempo que debería ir a la ciencia, no a las hojas de cálculo.",
      p3title: "Brechas de competencias invisibles",
      p3: "Las hojas de cálculo no pueden saber si la persona asignada está realmente certificada para esa técnica IVF — un riesgo silencioso pero directo para los pacientes.",
    },
    solution: {
      badge: "La Solución",
      title: "LabRota automatiza la complejidad",
      sub: "Diseñado exclusivamente para laboratorios IVF — LabRota entiende las competencias de embriólogos, la cobertura de procedimientos y la naturaleza crítica de cada turno.",
    },
    features: {
      title: "Todo lo que tu laboratorio IVF necesita",
      sub: "Construido desde cero para laboratorios de fertilidad — no es otra herramienta genérica de turnos con apariencia sanitaria.",
      items: [
        { title: "Configuración con IA", body: "Comparte tus hojas de cálculo o rotas actuales. Nuestra IA las lee, extrae tu equipo, turnos y asignaciones de procedimientos, y configura tu laboratorio automáticamente — en una sola sesión." },
        { title: "Rotas Inteligentes con IA", body: "Un clic y la IA de LabRota organiza todo el horario de turnos — equilibrando carga, respetando ausencias aprobadas y asegurando que cada procedimiento tiene asignado el personal certificado correcto." },
        { title: "Control de Competencias", body: "LabRota sabe qué procedimientos domina cada miembro del equipo y señala las brechas en tiempo real — sin adivinanzas sobre quién puede cubrir qué." },
        { title: "Gestión de Ausencias", body: "El equipo solicita ausencias en la app, los managers aprueban con un clic — los saldos se actualizan automáticamente en la rota." },
        { title: "Saldo de Vacaciones", body: "Consulta la liquidación y los saldos de vacaciones en tiempo real de cada persona. Los managers ven el estado del equipo de un vistazo — actualización automática cuando se solicita, aprueba o disfruta una ausencia." },
        { title: "Edición con Arrastrar y Soltar", body: "Ajusta cualquier rota generada por IA con un simple arrastrar y soltar. Las alertas de brechas y cobertura se actualizan en tiempo real mientras mueves los turnos." },
        { title: "Cambios de Turno", body: "El equipo puede solicitar cambios de turno directamente desde la app. Los managers revisan y aprueban — la cobertura se mantiene automáticamente y todos reciben la notificación al instante." },
        { title: "Sincronización Outlook", body: "Conecta los calendarios de Outlook del equipo y los eventos de fuera de oficina se convierten automáticamente en ausencias en LabRota — sin entrada manual, sin ausencias olvidadas." },
      ],
    },
    how: {
      badge: "Cómo funciona",
      title: "De la configuración a la rota publicada en minutos",
      steps: [
        { title: "Importamos tus rotas actuales", body: "Envíanos tus hojas de cálculo. Nuestra IA extrae tu equipo, patrones de turno y certificaciones de procedimientos — tu laboratorio queda preconfigurado antes de tu primer inicio de sesión." },
        { title: "Genera con IA", body: "Pulsa Generar. La IA de LabRota analiza disponibilidad, competencias certificadas y ausencias aprobadas de todo el equipo y construye la rota óptima automáticamente — en menos de un minuto." },
        { title: "Revisa y ajusta", body: "Arrastra y suelta para hacer ajustes. LabRota señala brechas de competencias y problemas de cobertura en tiempo real mientras editas." },
        { title: "Publica y notifica", body: "Publica la rota con un clic. Tu equipo recibe la notificación al instante. Exporta a PDF o XLS para registros." },
      ],
      stat1: { value: "70%", label: "menos tiempo construyendo rotas", sub: "prom. frente al flujo con hojas de cálculo" },
      stat2: { value: "< 1 min", label: "para generar una rota completa", sub: "con IA — de cero a publicada" },
      stat3: { value: "0", label: "skill gaps perdidos", sub: "la IA los detecta todos" },
    },
    pricing: {
      title: "Precios simples y transparentes",
      sub: "Precio por persona. Crece o reduce según el tamaño de tu equipo.",
      monthly: "Mensual",
      annual: "Anual",
      save: "Ahorra 2 meses",
      staffLabel: "Personas en el equipo",
      perMonthUnit: "/mes",
      perAnnualUnit: "/mes, facturado anualmente",
      perPersonRate: "€5 por persona",
      promo: "Oferta de lanzamiento",
      features: [
        "Generación de rotas con IA",
        "Solicitudes de cambio de turno",
        "Control de competencias y detección de brechas",
        "Gestión de ausencias y saldo de vacaciones",
        "Sincronización calendario Outlook",
        "Exportación PDF y XLS",
        "Configuración asistida por IA desde tus rotas actuales",
        "Soporte prioritario",
      ],
      cta: "Solicitar una Demo",
    },
    cta: {
      title: "¿Listo para simplificar la planificación de tu laboratorio?",
      sub: "Únete a los laboratorios IVF que han sustituido las hojas de cálculo por rotas inteligentes con IA. Reserva una demo de 30 minutos — sin compromiso.",
      btn: "Solicitar una Demo",
    },
    footer: {
      tagline: "Horarios inteligentes para laboratorios IVF.",
      product: "Producto",
      legal: "Legal",
      contact: "Contacto",
      links: {
        features: "Funciones",
        pricing: "Precios",
        login: "Iniciar sesión",
        privacy: "Política de Privacidad",
        terms: "Términos de Servicio",
        gdpr: "RGPD",
      },
      copy: "© 2026 LabRota. Todos los derechos reservados.",
    },
  },
}

export type Lang = keyof typeof content
export type Content = typeof content["en"]
